[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_SPOTIFY_CLIENT_ID,VITE_REDIRECT_URI" }

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
